// cards.js
const challengeCards = [
  {
    id: "card_walk",
    title: "Take a 5-minute walk",
    description: "Step outside or pace indoors — move your body for just 5 minutes.",
    baseCost: 10,
    multiplier: 0.5,
    tags: ["health", "quick", "movement"],
  },
  {
    id: "card_message",
    title: "Send a kind message",
    description: "Text or email someone just to let them know you appreciate them.",
    baseCost: 15,
    multiplier: 0.7,
    tags: ["social", "kindness", "connection"],
  },
  {
    id: "card_meditate",
    title: "Do 1 minute of deep breathing",
    description: "Pause. Close your eyes. Inhale deeply, exhale slowly. Repeat for 1 minute.",
    baseCost: 8,
    multiplier: 0.3,
    tags: ["mindfulness", "calm", "quick"],
  },
  {
    id: "card_stretch",
    title: "Stretch for 2 minutes",
    description: "Gently stretch your arms, back, or legs for two full minutes.",
    baseCost: 12,
    multiplier: 0.4,
    tags: ["health", "movement", "energizing"],
  },
  {
    id: "card_water",
    title: "Drink a glass of water",
    description: "Hydrate! Pour and drink a glass of clean water.",
    baseCost: 5,
    multiplier: 0.2,
    tags: ["health", "quick", "basic"],
  },
  {
    id: "card_dance",
    title: "Dance to one song",
    description: "Put on a favorite tune and move like no one's watching.",
    baseCost: 20,
    multiplier: 1.0,
    tags: ["fun", "movement", "energy"],
  },
  {
    id: "card_journal",
    title: "Write down one thing you're grateful for",
    description: "Take a moment to write down a small win or something you're thankful for.",
    baseCost: 10,
    multiplier: 0.5,
    tags: ["mindfulness", "gratitude", "reflection"],
  },
  {
    id: "card_breath",
    title: "Take 3 deep breaths",
    description: "Center yourself with three deep, intentional breaths.",
    baseCost: 4,
    multiplier: 0.15,
    tags: ["calm", "quick", "breathing"],
  },
  {
    id: "card_stand",
    title: "Stand up and stretch your legs",
    description: "Step away from your screen, stand, and move a bit.",
    baseCost: 6,
    multiplier: 0.25,
    tags: ["health", "break", "movement"],
  }
];
